language: php

matrix:
  include:
    - php: 7.1
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.1
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer update --no-interaction --prefer-dist $COMPOSER_FLAGS

script:
  - composer tests
